first commit...
Problem:   File "C:\Users\Quepali\Dropbox\Dokumenter\IS-206\Assignment
3\Udacity\Lesson4-is206\lesson4-is206\main.py", line 224, in done
u = User.register(self.username, self.password, self.email)
File "C:\Users\Quepali\Dropbox\Dokumenter\IS-206\Assignment
3\Udacity\Lesson4-is206\lesson4-is206\main.py", line 106, in register
email = email)
File "C:\Program Files
(x86)\Google\google_appengine\google\appengine\ext\db\__init__.py", line
970, in __init__
prop.__set__(self, value)
File "C:\Program Files
(x86)\Google\google_appengine\google\appengine\ext\db\__init__.py", line
614, in __set__
value = self.validate(value)
File "C:\Program Files
(x86)\Google\google_appengine\google\appengine\ext\db\__init__.py", line
2841, in validate
value = super(StringProperty, self).validate(value)
File "C:\Program Files
(x86)\Google\google_appengine\google\appengine\ext\db\__init__.py", line
641, in validate
raise BadValueError('Property %s is required' % self.name)
BadValueError: Property name is required